name: Publish ST Schemas

on:
  push:
    branches:
      - master
    paths:
      - "st-schemas/**"

jobs:
  publish-schemas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Create or switch to st-schemas branch
        run: |
          # Check if st-schemas branch exists
          if git show-ref --verify --quiet refs/heads/st-schemas; then
            git checkout st-schemas
            git reset --hard origin/master
          else
            git checkout -b st-schemas
          fi

      - name: Prepare st-schemas branch
        run: |
          # Remove all files and directories except st-schemas
          find . -maxdepth 1 ! -name '.' ! -name '..' ! -name '.git' ! -name 'st-schemas' -exec rm -rf {} +

          # Move contents of st-schemas to root
          mv st-schemas/* ./
          rmdir st-schemas

          # Remove any remastering hidden files/directories except .git
          find . -maxdepth 1 -name '.*' ! -name '.git' -exec rm -rf {} + 2>/dev/null || true

      - name: Commit and push changes
        run: |
          # Check if there are changes to commit
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "Update ST schemas from master branch

          This commit contains the latest schemas from the st-schemas directory.
          Auto-generated by GitHub Actions."
            git push origin st-schemas --force
          else
            echo "No changes to commit"
          fi
